POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "TEST - 4.19: Blog List Expansion, step 7",
    "author": "NOMA 4.19",
    "url": "https://test.com",
    "likes": 123
}